### ISSUE TITLE
Left clicking on a card table with an axe crashes the game

### ISSUE THREAD

**Issue by powmonk** [Epidra/CasinoCraft#3]
Possibly just left clicking, haven't been able to test fully.

java.lang.NoSuchMethodError: 'boolean net.minecraftforge.common.ForgeHooks.canHarvestBlock(net.minecraft.world.level.block.state.BlockState, net.minecraft.world.entity.player.Player, net.minecraft.world.level.BlockGetter, net.minecraft.core.BlockPos)'
        at mod.casinocraft.block.BlockCardTableBase.m_5880_(BlockCardTableBase.java:91) ~[CasinoCraft_1.17.1_v15.jar%2342!:1.0]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60625_(BlockBehaviour.java:512) ~[server-1.17.1-20210706.113038-srg.jar%2393!:?]
        at net.minecraft.server.level.ServerPlayerGameMode.m_7391_(ServerPlayerGameMode.java:161) ~[server-1.17.1-20210706.113038-srg.jar%2393!:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7502_(ServerGamePacketListenerImpl.java:941) ~[server-1.17.1-20210706.113038-srg.jar%2393!:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(SourceFile:34) ~[server-1.17.1-20210706.113038-srg.jar%2393!:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(SourceFile:8) ~[server-1.17.1-20210706.113038-srg.jar%2393!:?]
        at net.minecraft.network.protocol.PacketUtils.m_131356_(SourceFile:21) ~[server-1.17.1-20210706.113038-srg.jar%2393!:?]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[server-1.17.1-20210706.113038-srg.jar%2393!:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(SourceFile:151) ~[server-1.17.1-20210706.113038-srg.jar%2393!:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(SourceFile:23) ~[server-1.17.1-20210706.113038-srg.jar%2393!:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:775) ~[server-1.17.1-20210706.113038-srg.jar%2393!:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:162) ~[server-1.17.1-20210706.113038-srg.jar%2393!:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(SourceFile:125) ~[server-1.17.1-20210706.113038-srg.jar%2393!:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:758) ~[server-1.17.1-20210706.113038-srg.jar%2393!:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:752) ~[server-1.17.1-20210706.113038-srg.jar%2393!:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18699_(SourceFile:110) ~[server-1.17.1-20210706.113038-srg.jar%2393!:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:737) ~[server-1.17.1-20210706.113038-srg.jar%2393!:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:687) ~[server-1.17.1-20210706.113038-srg.jar%2393!:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.17.1-20210706.113038-srg.jar%2393!:?]

**Comment by powmonk** [comment]
Yeah it's just left clicking, doesn't matter what's in your hand.

**Comment by powmonk** [comment]
1.17 btw, the latest version on curseforge

**Comment by Epidra** [comment]
I'm currently quite busy, so a patch might take a while.

**Comment by Flanks255** [comment]
"canHarvestBlock" changed names in 37.0.31 back in august.
it is now "isCorrectToolForDrops"
I could throw a PR your way with it fixed if that would make it easier.

**Comment by Epidra** [comment]
I do not take PRs, don't like people meddling with my code in my repo. But your comment helped fixing the crash. So, thanks.
